### ISSUE TITLE
License not working with version 3

### ISSUE THREAD

**Issue by malle-pietje** [cnj-digital/seotamic#27] opened 2023-02-27 15:07 UTC
I purchased a **Seotamic Lite** license on **2023-02-16** 05:08:32:
![image](https://user-images.githubusercontent.com/12016131/221600027-29ee7d36-d54d-4f74-b0ee-b7e262990ae7.png)

This license doesn't appear to be working with version 3. Why is that the case?

**Comment by malle-pietje** [comment] 2023-02-27 15:17
OK, because I really need to move forward I decided to purchase yet another Lite license but Statamic checkout isn't allowing that:
![image](https://user-images.githubusercontent.com/12016131/221603119-fd115847-6b42-419d-aa39-8c107223a415.png)

Something looks broken here...

**Comment by martink635** [comment] 2023-02-28 10:01
Thanks for reporting this! The previous license will/should carry over to the v3 Lite version. 

Will look into this and how to fix it.

**Comment by martink635** [comment] 2023-02-28 10:09
It seems I am able to add it to the cart now (not sure what was wrong, the marketplace is not ours…)
I also reduced the minimum version, I think this will solve the license issue if you bought the v2 version.

If you still have problems with this, feel free to reopen the issue.

**Comment by malle-pietje** [comment] 2023-02-28 11:30
Thanks for the reply. Still not working though, even after syncing the license info:
![image](https://user-images.githubusercontent.com/12016131/221841019-f08caec0-2840-42d8-b6b6-349960c4c65f.png)

PS: I'm not able to reopen the issue myself...

**Comment by martink635** [comment] 2023-02-28 11:34
Not sure how to handle this, I will ask the Statamic team for advice.

I will keep you updated in this issue & I will reopen it.

**Comment by malle-pietje** [comment] 2023-02-28 11:43
Thanks, let me know if you need any info from me.

**Comment by Josh-bey-activelogic** [comment] 2023-03-01 01:38
I am also having this issue.

**Comment by malle-pietje** [comment] 2023-03-01 08:09
Could #32 be related to this or should the plugin work, even without a “valid” license?

**Comment by malle-pietje** [comment] 2023-03-01 08:54
> I am also having this issue.

Are your SEO tags being rendered in the final HTML?

**Comment by malle-pietje** [comment] 2023-03-01 10:23
Okay, I decided to purchase a new PRO license and this now works. Probably the initially purchased Lite license is "broken"?

May I recommend adding a brief note to the README.md indicating that you need to update the `statamic/editions.php` file when using a PRO license? Took me some digging to find this out (first-time Statamic user here, quite experienced with Laravel though).

**Comment by malle-pietje** [comment] 2023-03-01 10:24
Leaving the issue open because of @Josh-bey-activelogic 's input.

**Comment by martink635** [comment] 2023-03-01 11:31
This is our first addon with editions, I thought that Statamic did that automatically for you.

> Okay, I decided to purchase a new PRO license and this now works. Probably the initially purchased Lite license is "broken"?
> 
> May I recommend adding a brief note to the README.md indicating that you need to update the `statamic/editions.php` file when using a PRO license? Took me some digging to find this out (first-time Statamic user here, quite experienced with Laravel though).

This is our first addon with editions, I thought that Statamic did that automatically for you. Sorry for the bad experience. Will notify the Statamic team and update the Readme regarding this.

**Comment by malle-pietje** [comment] 2023-03-01 11:42
> This is our first addon with editions, I thought that Statamic did that automatically for you.
> 
> > Okay, I decided to purchase a new PRO license and this now works. Probably the initially purchased Lite license is "broken"?
> > May I recommend adding a brief note to the README.md indicating that you need to update the `statamic/editions.php` file when using a PRO license? Took me some digging to find this out (first-time Statamic user here, quite experienced with Laravel though).
> 
> This is our first addon with editions, I thought that Statamic did that automatically for you. Sorry for the bad experience. Will notify the Statamic team and update the Readme regarding this.

Thanks for the feedback.

**Comment by beatwiz** [comment] 2023-03-01 12:26
I am also having this issue. Lite version is outputting licence warnings even without upgrade to 3.0. 
PRO 3.0 fresh install works.

Looking forward to an update, if possible. Many thanks in advance!

**Comment by malle-pietje** [comment] 2023-03-01 16:56
Yes, that was what I did. I simply didn't have the time to spend more time troubleshooting this... The Lite license still shows the same issue when assigned to this site.

**Comment by martink635** [comment] 2023-03-01 17:27
Thanks for the reports, sorry for the inconvenience.

As soon as I receiver more information, I will update you. Like it says above, a valid v2 license transfer over to the new v3 lite license.

**Comment by martink635** [comment] 2023-03-01 17:39
I've just purchased a fresh LITE license to test it on a new site and it shows as "licensed" in the CP. Not sure if anything happened.

This is not in regards to the old v2 licenses carrying over.

Feel free to use this license to test it out (valid for 3 uses, for the LITE version): `YVGBNR`

**Comment by leganz** [comment] 2023-03-06 06:44
Cause this affecting multiple clients of us.
We are running multiple instances where we use v2.1 of the plugin. We bought ~8 copies of the licence back in october and now every customer receives this warning although we are using statamic pro and purchased a bunch of licences..

I thought it might be "fixable" by going back to v2 but due to the fact that it only support php 7.4 we can't. 
So how should be proceed, cause telling my customers that you just increased the fee (backwards) is kind of weirrd...

**Comment by martink635** [comment] 2023-03-06 07:40
@leganz 

The idea was that the Lite v3 version is a free upgrade from v2. But I don't think that we can solve this by ourselves (waiting for a reply from the Statamic Team). I've sent you an email please check it out.

> I thought it might be "fixable" by going back to v2 but due to the fact that it only support php 7.4 we can't. So how should be proceed, cause telling my customers that you just increased the fee (backwards) is kind of weirrd...

This was not meant to be the case, and like stated a v2 license carries over to the v3 lite one. Just need to make this work with the Statamic Marketplace :)

**Comment by andylarkum** [comment] 2023-03-10 16:40
I'm having the same/similar(?!) issue
Having not done any dev on my sight for several months, I ran composer update. Site worked fine, but told me that SEOtamic had an update beyond my license. 
I went and paid for the Lite license.
However, on returning to add the license key to my dev site, I now can't navigate to anywhere.
 - Invalid edition [lite] for addon cnj/seotamic

So I checked on here, saw the migration required, so ran:
`php artisan seotamic:migrate

   Exception

  Invalid edition [lite] for addon cnj/seotamic

  at vendor/statamic/cms/src/Extend/Addon.php:447
    443▕     {
    444▕         $configured = config('statamic.editions.addons.'.$this->package());
    445▕
    446▕         if ($configured && ! $this->editions()->contains($configured)) {
  ➜ 447▕             throw new \Exception("Invalid edition [$configured] for addon ".$this->package());
    448▕         }
    449▕
    450▕         return $configured ?? $this->editions()->first();
    451▕     }`

So yeah...erm.....

**Comment by martink635** [comment] 2023-03-10 21:04
> I'm having the same/similar(?!) issue Having not done any dev on my sight for several months, I ran composer update. Site worked fine, but told me that SEOtamic had an update beyond my license. I went and paid for the Lite license. However, on returning to add the license key to my dev site, I now can't navigate to anywhere.
> 
> * Invalid edition [lite] for addon cnj/seotamic
> 
> So I checked on here, saw the migration required, so ran: `php artisan seotamic:migrate` ...and got:
> 
> Exception
> 
> Invalid edition [lite] for addon cnj/seotamic
> 
> at vendor/statamic/cms/src/Extend/Addon.php:447 443▕ { 444▕ $configured = config('statamic.editions.addons.'.$this->package()); 445▕ 446▕ if ($configured && ! $this->editions()->contains($configured)) { ➜ 447▕ throw new \Exception("Invalid edition [$configured] for addon ".$this->package()); 448▕ } 449▕ 450▕ return $configured ?? $this->editions()->first(); 451▕ }
> 
> So yeah...erm.....

We've updated and migrated several sites, without this issue. (not the license one)

Care to share some more info? Latest Statamic?

**Comment by andylarkum** [comment] 2023-03-11 08:09
> > I'm having the same/similar(?!) issue Having not done any dev on my sight for several months, I ran composer update. Site worked fine, but told me that SEOtamic had an update beyond my license. I went and paid for the Lite license. However, on returning to add the license key to my dev site, I now can't navigate to anywhere.
> > 
> > * Invalid edition [lite] for addon cnj/seotamic
> > 
> > So I checked on here, saw the migration required, so ran: `php artisan seotamic:migrate` ...and got:
> > Exception
> > Invalid edition [lite] for addon cnj/seotamic
> > at vendor/statamic/cms/src/Extend/Addon.php:447 443▕ { 444▕ $configured = config('statamic.editions.addons.'.$this->package()); 445▕ 446▕ if ($configured && ! $this->editions()->contains($configured)) { ➜ 447▕ throw new \Exception("Invalid edition [$configured] for addon ".$this->package()); 448▕ } 449▕ 450▕ return $configured ?? $this->editions()->first(); 451▕ }
> > So yeah...erm.....
> 
> We've updated and migrated several sites, without this issue. (not the license one)
> 
> Care to share some more info? Latest Statamic?

I was perhaps a little stupid! My exact order of activity:

`composer update`
`php artisan serve`
 --> Here I spotted the upgrade available for SEOtamic, so went and paid for the lite license
 --> I think here I clicked on an upgrade button (honestly can't remember, so might be making that up(!)
 --> Then did some browsing to see where to enter the license...site started to error (as above)
`composer require cnj/seotamic`
 --> Site continuing to error, checked for upgrate instructions, found here
`php artisan seotamic:migrate`
`vi config/statamic/editions.php`
 --> To confirm lite
 --> Started searching for suggestions, found this issue

Composer.json says: "laravel/framework": "^9.0"
...but I can't prove that because all artisan commands give the same error, namely:
`Invalid edition [lite] for addon cnj/seotamic`

Should we move this to its own issue?

**Comment by beatwiz** [comment] 2023-03-20 18:00
@andylarkum I've reproduced all the steps, but didnt work on my setup. As soon as it installed 3.0.5 the red warning displays, with or without the editions.php change. Thanks though!

**Comment by martink635** [comment] 2023-11-10 13:54
I am closing this, since it's out of our hands. Anyone that has issues, please contact me on my email in the previous comment and I will help asap. Thanks!

**Closed by martink635** 2023-11-10 13:54 UTC
